### ISSUE TITLE
Add support for "authentication database"

### ISSUE THREAD

**Issue by mahesh-pardeshi17** [datanucleus/datanucleus-mongodb#42]
## Bug Report : https://github.com/mahesh-pardeshi17/test-jdo

As per documentation provided by DataNucleus for MongoDB datastore, I couldn't found any property to setup a authentication database neither a MongoDB Standard Connection String Format **mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]** isn't fully supported. I got to know from above, DataNucleus missed [?options] parameter out of it.

Ultimately **mongodb://username:password@host:port/database?authSource=admin**
MongoDB Native Connection URL is working fine to connect to database with authentication using extra option authSource=authdatabase natively, which isn't working with DataNucleus.

**Comment by andyjefferson** [comment]
A PULL REQUEST should be on project "datanucleus-mongodb" and it is to CONTRIBUTE the feature. No test is a PULL REQUEST

**Comment by mahesh-pardeshi17** [comment]
Intention to send a test along with issue, The pull request captured due to my confusion.

**Comment by andyjefferson** [comment]
Sadly a "test" in this case does not demonstrate anything, since it doesn't show what "feature" you are expecting; quoting in the description some MongoDB "URL" that is not the DataNucleus accepted URL doesn't say anything unless the person understands what you are talking about, which I don't. 

The only way anything like this will ever happen is for you to contribute it.

**Comment by andyjefferson** [comment]
Still no adequate definition of what this is, so closing. Post a full definition, preferably with an associated PULL REQUEST contributing the feature, and this can be re-opened
